### PR TITLE
reimplemented memexec

### PR DESCRIPTION
**Pull request by UlrichBerntien**
* The Perl script behind the memexec function is stored in the resources directory.
* New but not tested: other architectures since x86_64 should be possible.
* The Perl script is stored gzip and uuencoded to obfuscate the syscall.
* uuencode and not base64 is used because uudecode is part of the busybox and base64 is not part of the busybox but. So I hope uudecode is on more systems then base64.

### CODE REVIEW

**Comment by 0x27** [comment]
uuencode/uudecode are missing on a lot of systems, so I wouldn't merge this just yet.

**Comment by UlrichBerntien** [comment]
Thank you. I changed from uuencode/uudecode to the base64 tool. Now the combination gzip + base64 is used to encode/decode the memexec Perl script. I hope this is supported by more systems.

If you know a better tool combination I will use it. Another option is to store the plain text of the Perl script in o.rc. But the original o.rc version uses an obfuscation so I want to support obfuscation also.

**Comment by UlrichBerntien** [comment]
Now the memexec function should be able to download and execute script files.

A script file must start with the "#!". This two bytes will be checked and then the script file executed via the env tool.

**Comment by UlrichBerntien** [comment]
Added python2 and python3 implementation of memexec.

Now the download and execution of binary programs and script files should be work with python3, python2 or perl.

**Pull request merged**
